{% set name = "persist_ext" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/persist_ext-{{ version }}.tar.gz
  sha256: e3cc30d8142b37225c7662e8292889ebcdd7bf3be12e2c545bd9d2c956098e82

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.8
    - altair >=5
    - jupyterlab >=4
    - pandas >=0.25
    - anywidget
    - ipywidgets
    - lzstring
    - traittypes ==0.2.1
    - pyarrow
    - fastparquet
    - scikit-learn

test:
  imports:
    - persist_ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/visdesignlab/persist
  summary: JupyterLab extension to enable persistent interactive visualizations in JupyterLab notebooks.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
